version: '3.8'

services:
  backend:
    build: ./backend
    container_name: prediction-market-backend
    restart: unless-stopped
    environment:
      - ETHEREUM_RPC=${ETHEREUM_RPC:-https://sepolia.infura.io/v3/your-api-key}
      - PORT=8080
      - NETWORK_ID=${NETWORK_ID:-11155111}
      - PRIVATE_KEY=${PRIVATE_KEY:-}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - prediction-market

  frontend:
    build: ./web
    container_name: prediction-market-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - prediction-market

networks:
  prediction-market:
    driver: bridge